In [1]:
import numpy as np
a = np.arange(2,7)
c = np.arange(3, 8)
print(a)
print(c)
print(np.dot(a,c))

[2 3 4 5 6]
[3 4 5 6 7]
110


In [2]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])

In [3]:
print(np.matmul(a,b))

[[4 1]
 [2 2]]


In [4]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
print(np.matmul(a, b))


[[4 1]
 [2 2]]
