# Collections :- list, tuple, dictionary, set

## List
- List is collection of heterogeneous items
- List size can be changed dynamically

In [1]:
# declaration of a list
my_list = [1,7,58,24, 'BCSE101E', 'NLP', 99.8,'Windows']

In [2]:
# accessing elements of list - list index starts from 0
print(my_list[2])
print(my_list[1])
print(my_list[5])

58
7
NLP


In [3]:
# re-assigning an list index
print('before re-assigning', my_list)
my_list[3] = 'new_item'
print(' After re-assigning' , my_list)

before re-assigning [1, 7, 58, 24, 'BCSE101E', 'NLP', 99.8, 'Windows']
 After re-assigning [1, 7, 58, 'new_item', 'BCSE101E', 'NLP', 99.8, 'Windows']


In [4]:
# slicing and striding over list
print(my_list[2:7])
print(my_list[2:7:2])

[58, 'new_item', 'BCSE101E', 'NLP', 99.8]
[58, 'BCSE101E', 99.8]


In [5]:
# List can also be accessed with negative indxing
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-5])

Windows
99.8
NLP
new_item


In [6]:
my_list.append(199)
print(my_list[-1])

199


In [9]:
print(my_list[:4])
my_list.insert(2, 96)
print(my_list[:4])

[1, 7, 58, 'new_item']
[1, 7, 96, 58]


## Tuples
- tuple is also a collection of heteregenous elements

In [ ]:
#tuple declaration
my_tup = (1,'ram', 67, 3.14, 'BCSE101E')
print(my_tup)


(1, 'ram', 67, 3.14, 'BCSE101E')


In [ ]:
# Accessing elements of tuple - tuple indexing start from zero (0)
print(my_tup[1])
print(my_tup[4])
print(my_tup[0])

ram
BCSE101E
1


In [17]:
list_loc = [ (2,3) , (4,5), (7,13)]
print(list_loc[1][0])

4


## Dictionary
- a key-value pair

In [13]:
d= {1: 'ram', 2 :'shyam', 7: 'Mohan'}

In [ ]:
print(d)

{1: 'ram', 2: 'shyam', 7: 'Mohan'}


In [16]:
print(d[1])

ram


In [15]:
print(d[7])

Mohan


In [ ]:
print(d.keys())

dict_keys([1, 2, 7])


In [ ]:
print(d.values())

dict_values(['ram', 'shyam', 'Mohan'])


In [ ]:
print(d.items())

dict_items([(1, 'ram'), (2, 'shyam'), (7, 'Mohan')])


In [ ]:
keys_list = d.keys()
print(keys_list)
print(type(keys_list))

dict_keys([1, 2, 7])
<class 'dict_keys'>


In [ ]:
values_list = d.values()
print(values_list)
print(type(values_list))

dict_values(['ram', 'shyam', 'Mohan'])
<class 'dict_values'>


In [12]:
print(d[1])

NameError: ignored

In [ ]:
x = 5
print(x==5)

True


In [ ]:
x = None
print(x==None)

True


## Declaring an array with the help of `numpy` module

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a_2d = np.array([ [1,2,3],
                 [4,5,6],
                 [7,8,9]
                ])
print(a_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Assigments:
- difference between an array and list