# Collections - list, tuple, dictionary, 

## List
- List is collection of heterogeneous items
- List size can be changed dynamically

In [3]:
# declaration of a list
my_list = [1,7,58,24, 'BCSE101E', 'NLP', 99.8,'Windows']

In [5]:
# accessing elements of list - list index starts from 0
print(my_list[2])
print(my_list[1])
print(my_list[5])

58
7
NLP


In [7]:
# re-assigning an list index
print('before re-assigning', my_list)
my_list[3] = 'new_item'
print(' After re-assigning' , my_list)

before re-assigning [1, 7, 58, 24, 'BCSE101E', 'NLP', 99.8, 'Windows']
 After re-assigning [1, 7, 58, 'new_item', 'BCSE101E', 'NLP', 99.8, 'Windows']


In [11]:
# slicing and striding over list
print(my_list[2:7])
print(my_list[2:7:2])

[58, 'new_item', 'BCSE101E', 'NLP', 99.8]
[58, 'BCSE101E', 99.8]


In [6]:
# List can also be accessed with negaative indxing
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-5])

Windows
99.8
NLP
24


## Tuples
- tuple is also a collection of heteregenous elements

In [28]:
#tuple declaration
my_tup = (1,'ram', 67, 3.14, 'BCSE101E')
print(my_tup)

(1, 'ram', 67, 3.14, 'BCSE101E')


In [30]:
# Accessing elements of tuple - tuple indexing start from zero (0)
print(my_tup[1])
print(my_tup[4])
print(my_tup[0])

ram
BCSE101E
1


## Dictionary
- a key-value pair

In [16]:
d= {1: 'ram', 2 :'shyam', 7: 'Mohan'}

In [17]:
print(d)

{1: 'ram', 2: 'shyam', 7: 'Mohan'}


In [19]:
print(d.keys())

dict_keys([1, 2, 7])


In [20]:
print(d.values())

dict_values(['ram', 'shyam', 'Mohan'])


In [21]:
print(d.items())

dict_items([(1, 'ram'), (2, 'shyam'), (7, 'Mohan')])


In [24]:
keys_list = d.keys()
print(keys_list)
print(type(keys_list))

dict_keys([1, 2, 7])
<class 'dict_keys'>


In [25]:
values_list = d.values()
print(values_list)
print(type(values_list))

dict_values(['ram', 'shyam', 'Mohan'])
<class 'dict_values'>


In [7]:
x = 5
print(x==5)

True


In [9]:
x = None
print(x==None)

True


## Declaring an array with the help of `numpy` module

In [11]:
import numpy as np

In [13]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
a_2d = np.array([ [1,2,3], 
                 [4,5,6], 
                 [7,8,9]
                ])
print(a_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Assigments:
- difference between an array and list